---
- name: Install RPM packages
  dnf:
    name:
    - gcc
    - libffi-devel
    - python3-cryptography
    - python3-devel
    - python3-flask
    - python3-pip
    state: present

- name: Install poetry Python package
  command: pip install poetry

- name: install python deps with poetry
  become_user: vagrant
  command:
    cmd: poetry install
    chdir: noggin

- name: Install the .bashrc
  copy:
    src: bashrc
    dest: /home/vagrant/.bashrc
    mode: 0644
    owner: vagrant
    group: vagrant

- name: Install noggin.cfg
  become_user: vagrant
  template:
    src: noggin.cfg
    dest: noggin.cfg

- name: compile the translations
  become_user: vagrant
  command:
    cmd: poetry run pybabel compile -d /home/vagrant/noggin/noggin/translations
    chdir: noggin

- name: Install the systemd unit files
  copy:
    src: "{{ item }}"
    dest: /etc/systemd/system/{{ item }}
    owner: vagrant
    group: vagrant
    mode: 0644
  loop:
    - synced-folder.service
    - noggin.service
  notify:
    - reload systemd
    - restart synced-folder
    - restart noggin

- name: Start the services using systemd
  systemd:
    state: started
    name: "{{ item }}"
    daemon_reload: yes
    enabled: yes
  loop:
    - synced-folder.service
    - noggin.service
