[tool.poetry]
name = "securitas"
version = "0.0.1"
description = "Securitas is a self-service portal for FreeIPA. The primary purpose of the portal is to allow users to sign up and manage their account information and group membership."

license = "MIT"

authors = [
    "Fedora Infrastructure <admin@fedoraproject.org>"
]

readme = 'README.md'  # Markdown files are supported

repository = "https://github.com/fedora-infra/securitas"
homepage = "https://github.com/fedora-infra/securitas"

keywords = ['security']

[tool.poetry.dependencies]
python = "^3.6"
cryptography = "^2.8"
flask = "^1.1"
flask-wtf = "^0.14"
python-freeipa = "^0.2"

[tool.poetry.dev-dependencies]
pytest = "^5.3"
pytest-cov = "^2.8"
sphinx = "^2.3"
mock = "^3.0"
beautifulsoup4 = "^4.8"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

[tool.black]
skip-string-normalization = true
