- name: reload systemd
  systemd:
    daemon_reload: yes

- name: reload user systemd
  systemd:
    scope: user
    daemon_reload: yes

- name: restart synced-folder
  systemd:
    name: synced-folder
    state: restarted

- name: restart noggin
  systemd:
    name: noggin
    state: restarted
